//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Re4QuadExtremeEditor.Properties {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Re4QuadExtremeEditor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BlackTexture {
            get {
                object obj = ResourceManager.GetObject("BlackTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] BoundaryBoxShaderFrag {
            get {
                object obj = ResourceManager.GetObject("BoundaryBoxShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] BoundaryBoxShaderVert {
            get {
                object obj = ResourceManager.GetObject("BoundaryBoxShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Box {
            get {
                object obj = ResourceManager.GetObject("Box", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Circle {
            get {
                object obj = ResourceManager.GetObject("Circle", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CircleTriggerZoneShaderFrag {
            get {
                object obj = ResourceManager.GetObject("CircleTriggerZoneShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CircleTriggerZoneShaderVert {
            get {
                object obj = ResourceManager.GetObject("CircleTriggerZoneShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CylinderDown {
            get {
                object obj = ResourceManager.GetObject("CylinderDown", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CylinderDownX {
            get {
                object obj = ResourceManager.GetObject("CylinderDownX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CylinderFull {
            get {
                object obj = ResourceManager.GetObject("CylinderFull", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CylinderSides {
            get {
                object obj = ResourceManager.GetObject("CylinderSides", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CylinderTop {
            get {
                object obj = ResourceManager.GetObject("CylinderTop", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] CylinderTopX {
            get {
                object obj = ResourceManager.GetObject("CylinderTopX", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] GridShaderFrag {
            get {
                object obj = ResourceManager.GetObject("GridShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] GridShaderVert {
            get {
                object obj = ResourceManager.GetObject("GridShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HorizontalDisable {
            get {
                object obj = ResourceManager.GetObject("HorizontalDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HorizontalYelow {
            get {
                object obj = ResourceManager.GetObject("HorizontalYelow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] ItemTrigggerRadius {
            get {
                object obj = ResourceManager.GetObject("ItemTrigggerRadius", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] ItemTrigggerRadiusShaderFrag {
            get {
                object obj = ResourceManager.GetObject("ItemTrigggerRadiusShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] ItemTrigggerRadiusShaderVert {
            get {
                object obj = ResourceManager.GetObject("ItemTrigggerRadiusShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] LIT_Point {
            get {
                object obj = ResourceManager.GetObject("LIT_Point", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] LitPointShaderFrag {
            get {
                object obj = ResourceManager.GetObject("LitPointShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] LitPointShaderVert {
            get {
                object obj = ResourceManager.GetObject("LitPointShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NoTexture {
            get {
                object obj = ResourceManager.GetObject("NoTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] ObjModelShaderFrag {
            get {
                object obj = ResourceManager.GetObject("ObjModelShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] ObjModelShaderVert {
            get {
                object obj = ResourceManager.GetObject("ObjModelShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] Plane {
            get {
                object obj = ResourceManager.GetObject("Plane", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] PlaneZoneShaderFrag {
            get {
                object obj = ResourceManager.GetObject("PlaneZoneShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] PlaneZoneShaderVert {
            get {
                object obj = ResourceManager.GetObject("PlaneZoneShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] RoomSelectModeShaderFrag {
            get {
                object obj = ResourceManager.GetObject("RoomSelectModeShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] RoomSelectModeShaderVert {
            get {
                object obj = ResourceManager.GetObject("RoomSelectModeShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] RoomShaderFrag {
            get {
                object obj = ResourceManager.GetObject("RoomShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] RoomShaderVert {
            get {
                object obj = ResourceManager.GetObject("RoomShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SquareDisable {
            get {
                object obj = ResourceManager.GetObject("SquareDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SquareRed {
            get {
                object obj = ResourceManager.GetObject("SquareRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SquareRedLookHorisontal {
            get {
                object obj = ResourceManager.GetObject("SquareRedLookHorisontal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SquareRedLookVertical {
            get {
                object obj = ResourceManager.GetObject("SquareRedLookVertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Transparent {
            get {
                object obj = ResourceManager.GetObject("Transparent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] TriggerZoneShaderFrag {
            get {
                object obj = ResourceManager.GetObject("TriggerZoneShaderFrag", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Byte[].
        /// </summary>
        internal static byte[] TriggerZoneShaderVert {
            get {
                object obj = ResourceManager.GetObject("TriggerZoneShaderVert", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VerticalDisable {
            get {
                object obj = ResourceManager.GetObject("VerticalDisable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VerticalRed {
            get {
                object obj = ResourceManager.GetObject("VerticalRed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Consulta um recurso localizado do tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WhiteTexture {
            get {
                object obj = ResourceManager.GetObject("WhiteTexture", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
